### ISSUE TITLE
修复：Jupyter Theme 样式污染问题

### ISSUE THREAD

**Issue by Z-J-wang** [Z-J-wang/render-jupyter-notebook-vue#94]
**Describe the bug**
@jupyterlab/theme-light-extension/style/theme.css 文件中的样式会覆盖code、tt、pre等标签的默认样式。具体如下：
```css
/*文件路径 @jupyterlab/theme-light-extension/style/theme.css*/

/*-----------------------------------------------------------------------------
| Copyright (c) Jupyter Development Team.
| Distributed under the terms of the Modified BSD License.
|----------------------------------------------------------------------------*/

@import './variables.css';

/* Set the default typography for monospace elements */
tt,
code,
kbd,
samp,
pre {
  font-family: var(--jp-code-font-family);
  font-size: var(--jp-code-font-size);
  line-height: var(--jp-code-line-height);
}

```

**Comment by Z-J-wang** [comment]
解决方法：重写`@jupyterlab/theme-light-extension/style/theme.css`文件，给code等标签增加前置class限制起生效范围。具体如下：

```css
/* 此文件重写了@jupyterlab/theme-light-extension/style/theme.css  中的部分样式
用于解决 tt、code、kbd、samp、pre 样式污染问题 */

@import '@jupyterlab/theme-light-extension/style/variables.css';

.lm-Widget tt,
.lm-Widget code,
.lm-Widget kbd,
.lm-Widget samp,
.lm-Widget pre {
  font-family: var(--jp-code-font-family);
  font-size: var(--jp-code-font-size);
  line-height: var(--jp-code-line-height);
}

```
